# These are supported funding model platforms

github: Skixkk # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://youupro.xyz/notes/nodes/tutorial/Watt_Toolkit%E4%B8%8B%E8%BD%BD&%E5%8A%A0%E9%80%9FGitHub%E6%95%99%E7%A8%8B.html
